clickhouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: clickhouse.clickhouse.svc.cluster.local
      port: 8123
      user: "{{ env_var('username', 'default')}}"
      password: "{{ env_var('password', '') }}"
      database: thelook
      schema: thelook
      cluster: default
      # Optional settings
      # secure: False
      # verify: False
      # connect_timeout: 10
      # send_receive_timeout: 300
      # sync_request_timeout: 5
      # compress: True
      # settings:
      #   mutations_sync: 1
